apiVersion: apps/v1
kind: DaemonSet 
metadata:
  name: todo-daemonset
  namespace: mateapp
  labels:
    app: daemonset_app
spec:
  selector:
    matchLabels: 
      app: daemonset_app
  template:
    metadata:
      labels:
        app: daemonset_app
    spec:
      containers:
        - name: curl-loop
          image: ikulyk404/busyboxplus:curl
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "Curling todoapp...";
                curl http://todoapp-service.todoapp.svc.cluster.local/api/ready;
                sleep 5;
              done
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

